import Head from 'next/head'
import Banner from '../components/Banner'
import BigCase from '../components/BigCase'
import Header from '../components/Header'
import SmallCase from '../components/SmallCase'
import LargeCase from '../components/LargeCase';
import Footer from '../components/Footer'


export default function Home({exploreData,cardData}) {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     {/* Header */}
     <Header/>

     {/* Banner */}
     <Banner/>

     {/* main */}
    <main className="w-3/4 mx-auto sm:px-16">
       <section className="pt-6 ">
         <h2 className="text-2xl font-semibold pb-5">Explore Nearby</h2>
         <div className="grid gap-4 grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3">
         {exploreData?.map(({img,distance,location})=>(
            <SmallCase img={img} distance={distance}
            location={location} key={location}/>
        ))}  
        </div>
       </section>
       <section className="pt-6">
          <h2>Live Anywhere</h2>
          <div className="flex space-x-2 overflow-scroll
          scrollbar-hide">

          {cardData?.map(({img,title}) =>(
           
           <BigCase img={img} title={title} key={title}/>
          
        ))}
          </div>
       
         
       </section>
       <section>
          <LargeCase 
          img="https://links.papareact.com/4cj"
          title="The Greatest Outdoors"
          description="Whishlists curated by Airbnb"
          buttonText="Get Inspired"/>
       </section>
    </main>
            <Footer/>
     
    </div>
  )
}


export async function getStaticProps(){
  const exploreData = await fetch('https://links.papareact.com/pyp').
  then(
    (res) => res.json()
  );


  const cardData = await fetch('https://links.papareact.com/zp1').
  then(
    (res)=> res.json()
  )

  return {
    props:{
      exploreData: exploreData,
      cardData: cardData
    }
  }
  
}
